using System;
using UnityEngine;
using UnityEngine.UI;
using Kamilunavo.OneMoreFloor.Core;
using Kamilunavo.OneMoreFloor.Gameplay;
using Kamilunavo.OneMoreFloor.Input;
using Kamilunavo.OneMoreFloor.Visuals;
namespace Kamilunavo.OneMoreFloor.UI
{
 public sealed class FloorHud:MonoBehaviour
 {
  public FloorCourse Course{get;private set;}public VirtualJoystick Joystick{get;private set;}public PressButton Jump{get;private set;}public bool ModalOpen=>_modal!=null;public bool ShopOpen=>_page=="shop";public bool CheckpointDecisionVisible=>_page=="checkpoint";public event Action UiPressed;
  private RectTransform _safe,_modal,_content,_coach;private Text _coachTitle,_coachBody,_coachSkipLabel;private Button _coachSkip;private bool _tutorialLayout;private int _selectedRealm=-1;private Text _height,_coins,_hint,_score,_pending,_action;private Image _progress;private RectTransform _timingMeter,_timingNeedle,_landingWindow,_perfectWindow;private Button _menu;private int _width,_heightScreen;private Vector2 _safeSize;private string _page="";private float _hintUntil,_nextVideoPoll;private Button _watchButton,_retryStoreButton;
  private static readonly Color Ivory=new(.97f,.92f,.82f),Ink=new(.035f,.11f,.14f),Navy=new(.035f,.14f,.16f,.97f),Gold=new(1,.73f,.12f),Purple=new(.12f,.18f,.26f),Blue=new(.06f,.63f,.76f),Muted=new(.75f,.83f,.90f);
  private FloorProfile P=>Course.Profile;public string T(string de,string en)=>P.Language=="en"?en:de;
  public void Initialize(FloorCourse course){Course=course;var canvas=UiFactory.Canvas();_safe=UiFactory.Panel(canvas.transform,"SafeArea",Color.clear,Vector2.zero,Vector2.one);_safe.gameObject.AddComponent<SafeAreaFitter>();
   _menu=UiFactory.Button(_safe,"Menu","",Navy,Color.white,Vector2.zero,Vector2.one,ShowHome);HudIcons.Add(_menu.transform,HudIcons.Kind.Menu);
   var height=UiFactory.Panel(_safe,"Height",Navy,Vector2.zero,Vector2.one);_height=UiFactory.Label(height,"Value","",20,new Vector2(.05f,.33f),new Vector2(.95f,.97f),TextAnchor.MiddleCenter,Color.white,FontStyle.Bold);_progress=UiFactory.Progress(height,new Vector2(.10f,.14f),new Vector2(.90f,.25f),new Color(.16f,.23f,.36f),Gold);
   var coins=UiFactory.Panel(_safe,"Crystals",Navy,Vector2.zero,Vector2.one);var gem=UiFactory.Panel(coins,"CrystalIcon",Color.clear,new Vector2(.04f,.18f),new Vector2(.31f,.82f));HudIcons.Add(gem,HudIcons.Kind.Crystal);gem.GetComponentInChildren<HudIcons>().color=Gold;_coins=UiFactory.Label(coins,"Value","",20,new Vector2(.30f,.05f),new Vector2(.95f,.95f),TextAnchor.MiddleCenter,Gold,FontStyle.Bold);
   var scorePanel=UiFactory.Panel(_safe,"Score",Navy,Vector2.zero,Vector2.one);_score=UiFactory.Label(scorePanel,"Value","",18,new Vector2(.04f,.03f),new Vector2(.96f,.97f),TextAnchor.MiddleCenter,Color.white,FontStyle.Bold);
   _hint=UiFactory.Label(_safe,"RouteHint","",17,Vector2.zero,Vector2.one,TextAnchor.MiddleCenter,Color.white,FontStyle.Bold);
   var outline=_hint.gameObject.AddComponent<Outline>();outline.effectColor=new Color(.01f,.04f,.09f,.95f);outline.effectDistance=new Vector2(1,-1);
   Joystick=VirtualJoystick.Create(_safe,Vector2.zero,Vector2.one);Jump=PressButton.Create(_safe,"",Vector2.zero,Vector2.one,true);Jump.Pressed+=()=>{if(P.RunBanked)ShowHome();else Course.LaunchTransfer();};_action=Jump.GetComponentInChildren<Text>();_action.fontSize=25;_action.resizeTextMaxSize=25;_action.fontStyle=FontStyle.Bold;Joystick.gameObject.SetActive(false);
   _timingMeter=UiFactory.Panel(_safe,"TimingMeter",Navy,Vector2.zero,Vector2.one);var meterTrack=UiFactory.Panel(_timingMeter,"MeterTrack",new Color(.33f,.41f,.39f),new Vector2(.05f,.30f),new Vector2(.95f,.70f));_landingWindow=UiFactory.Panel(meterTrack,"LandingWindow",new Color(.17f,.53f,.44f),Vector2.zero,Vector2.one);_perfectWindow=UiFactory.Panel(meterTrack,"PerfectWindow",Gold,Vector2.zero,Vector2.one);_timingNeedle=UiFactory.Panel(meterTrack,"ArrivalNeedle",Ivory,Vector2.zero,Vector2.one);foreach(var graphic in _timingMeter.GetComponentsInChildren<Graphic>())graphic.raycastTarget=false;
   _pending=UiFactory.Label(_safe,"PendingReward","",18,Vector2.zero,Vector2.one,TextAnchor.MiddleCenter,Gold,FontStyle.Bold);var pendingOutline=_pending.gameObject.AddComponent<Outline>();pendingOutline.effectColor=new Color(.01f,.04f,.09f,.95f);pendingOutline.effectDistance=new Vector2(1,-1);
   course.CheckpointReached+=ShowCheckpoint;course.Changed+=Refresh;course.Landed+=perfect=>Hint(perfect?T("PERFEKT!","PERFECT!"):T("Etappe geschafft","Step cleared"));course.Fell+=()=>Hint(T("Zurück am Kontrollpunkt","Back at checkpoint"));course.PortalCompleted+=ShowCompletion;
   CreateCoach();Layout();Refresh();if(P.Completed)ShowCompletion();else if(P.RunBanked)ShowBanked();else if(P.CheckpointDecisionPending)ShowCheckpoint();else ShowHome();
  }
  public Rect GameplayViewport{get{var cam=UnityEngine.Camera.main;if(cam==null||_pending==null||Jump==null)return new Rect(.08f,.23f,.84f,.54f);var pane=cam.pixelRect;float lower=(Mathf.Max(Mathf.Max(UiMetrics.ScreenRect((RectTransform)Jump.transform).yMax,!Course.TutorialActive&&_timingMeter!=null?UiMetrics.ScreenRect(_timingMeter).yMax:0),Course.TutorialActive&&_coach!=null?UiMetrics.ScreenRect(_coach).yMax:0)+12-pane.yMin)/Mathf.Max(1,pane.height),upper=(UiMetrics.ScreenRect((RectTransform)_pending.transform).yMin-12-pane.yMin)/Mathf.Max(1,pane.height);return Rect.MinMaxRect(.08f,Mathf.Clamp(lower,.08f,Course.TutorialActive?.58f:.43f),.92f,Mathf.Clamp(upper,.53f,.90f));}}
  private static void Place(RectTransform r,float x,float y,float w,float h,bool bottom=false){r.anchorMin=r.anchorMax=new Vector2(0,bottom?0:1);r.pivot=new Vector2(0,bottom?0:1);r.anchoredPosition=new Vector2(x,bottom?y:-y);r.sizeDelta=new Vector2(w,h);}
  private void Layout(){Canvas.ForceUpdateCanvases();float w=_safe.rect.width,h=_safe.rect.height;float target=UiMetrics.TargetSize(_safe,52),headerX=target+22;Place((RectTransform)_menu.transform,12,12,target,target);Place((RectTransform)_height.transform.parent,headerX,12,Mathf.Max(80,w-headerX-206),target);Place((RectTransform)_score.transform.parent,w-194,12,78,target);Place((RectTransform)_coins.transform.parent,w-108,12,96,target);Place((RectTransform)_hint.transform,headerX,target+18,w-headerX-74,26);
   _score.transform.parent.gameObject.SetActive(w>=340);if(w<340){Place((RectTransform)_height.transform.parent,headerX,12,Mathf.Max(80,w-headerX-118),target);}
   if(w<280){Place((RectTransform)_height.transform.parent,headerX,12,w-headerX-12,target);Place((RectTransform)_coins.transform.parent,w-90,target+20,78,target);Place((RectTransform)_hint.transform,12,target*2+26,w-24,24);}
   float buttonH=UiMetrics.TargetSize(_safe,62),buttonW=Mathf.Min(w-32,420);Place((RectTransform)Jump.transform,(w-buttonW)/2,18,buttonW,buttonH,true);Joystick.gameObject.SetActive(false);
   Place(_timingMeter,(w-buttonW)/2,18+buttonH+8,buttonW,36,true);_timingMeter.gameObject.SetActive(!Course.TutorialActive);
   Place((RectTransform)_hint.transform,12,target+22,w-24,26);Place((RectTransform)_pending.transform,12,target+50,w-24,24);
   if(_coach!=null){if(Course.TutorialActive&&w>h){Place((RectTransform)Jump.transform,w*.50f,18,w*.50f-12,buttonH,true);Place(_coach,12,18,w*.50f-24,buttonH,true);}else Place(_coach,12,18+buttonH+10,w-24,82,true);}_tutorialLayout=Course.TutorialActive;
   _width=Screen.width;_heightScreen=Screen.height;_safeSize=_safe.rect.size;
  }
  private void Update(){if(ShopOpen&&Time.unscaledTime>=_nextVideoPoll){_nextVideoPoll=Time.unscaledTime+1;if(_watchButton!=null)_watchButton.interactable=Course.Videos.CanWatch;if(_retryStoreButton!=null)_retryStoreButton.interactable=Course.Store.CanRetry;}if(_width!=Screen.width||_heightScreen!=Screen.height||_safeSize!=_safe.rect.size){Layout();if(ModalOpen)Reopen();}if(!ModalOpen&&Time.unscaledTime>_hintUntil)_hint.text=Course.IsTransferring?T("WECHSEL LÄUFT…","TRANSFERRING…"):P.RunBanked?T("Runde gesichert · Wähle einen Turm","Round banked · Choose a tower"):Course.Height==29?T("Turm geschafft!","Tower cleared!"):Course.PredictedHit==2?T("PERFECT-FENSTER · JETZT!","PERFECT WINDOW · NOW!"):Course.PredictedHit==1?T("LANDUNG MÖGLICH","LANDING WINDOW"):T("Warte auf die Landebucht","Wait for the landing bay");
   _menu.interactable=!Course.IsTransferring;
   _action.text=P.RunBanked?T("NEUE RUNDE","NEW ROUND"):Course.IsTransferring?T("UNTERWEGS…","IN FLIGHT…"):T("ETAGE WECHSELN","CHANGE FLOOR");var actionSurface=Course.IsTransferring||P.RunBanked?Navy:Course.PredictedHit==2?Gold:Blue;Jump.GetComponent<Image>().color=actionSurface;_action.color=UiFactory.Contrast(Color.white,actionSurface)>=4.5f?Color.white:new Color(.025f,.055f,.09f);
   UpdateMeter();UpdateCoach();_pending.text=T("IM RISIKO: ","AT RISK: ")+P.PendingCoins+T(" Münzen"," coins")+" · "+T("PERFECT ×","PERFECT ×")+P.PerfectChain;}
  private void UpdateMeter(){if(_timingMeter==null||Course.Steps.Count==0||Course.Height>=29)return;int next=Course.Height+1;float half=ElevatorRules.HalfBay(next)/6f,position=.5f+Course.Steps[next].transform.parent.GetComponent<ElevatorMotion>().At(Course.TimingClock+ElevatorRules.FlightSeconds).x/6f;_landingWindow.anchorMin=new Vector2(.5f-half,0);_landingWindow.anchorMax=new Vector2(.5f+half,1);_landingWindow.offsetMin=_landingWindow.offsetMax=Vector2.zero;_perfectWindow.anchorMin=new Vector2(.5f-half*.24f,0);_perfectWindow.anchorMax=new Vector2(.5f+half*.24f,1);_perfectWindow.offsetMin=_perfectWindow.offsetMax=Vector2.zero;_timingNeedle.anchorMin=new Vector2(Mathf.Clamp01(position)-.006f,-.3f);_timingNeedle.anchorMax=new Vector2(Mathf.Clamp01(position)+.006f,1.3f);_timingNeedle.offsetMin=_timingNeedle.offsetMax=Vector2.zero;}
  public void Refresh(){if(Course==null||P==null)return;if(_tutorialLayout!=Course.TutorialActive&&Jump!=null)Layout();UiFactory.HighContrast=P.HighContrast;var navy=Navy;navy.a=P.HighContrast?1:.95f;UiFactory.StyleButton(_menu,navy);_height.transform.parent.GetComponent<Image>().color=navy;_coins.transform.parent.GetComponent<Image>().color=navy;Jump.GetComponent<Image>().color=new Color(.03f,.06f,.10f,P.HighContrast?1:.74f);Joystick.GetComponent<Image>().color=new Color(.03f,.06f,.10f,P.HighContrast?.94f:.62f);
   foreach(var step in Course.Steps){var contrast=step.transform.parent.Find("RouteContrastRim");if(contrast!=null)contrast.gameObject.SetActive(P.HighContrast);}
   _score.text=T("PUNKTE\n","SCORE\n")+P.Score.ToString("N0");_height.text=T("ETAGE ","STAGE ")+(Course.Height+1)+" / 30";_coins.text=P.Crystals.ToString("N0",System.Globalization.CultureInfo.GetCultureInfo(P.Language=="de"?"de-DE":"en-US"));_progress.fillAmount=(Course.Height+1)/30f;var runner=Course.Player.GetComponentInChildren<RunnerAnimator>();runner?.Style(P.Style);}
  private void Hint(string text){_hint.text=text;_hintUntil=Time.unscaledTime+2.2f;}
  private void Tap(){UiPressed?.Invoke();}
  public void Close(){if(Course.Store?.IsPresenting==true||Course.Videos?.IsPresenting==true)return;if(_page!="checkpoint"&&P.CheckpointDecisionPending&&!P.RunBanked){ShowCheckpoint();return;}Tap();if(_modal!=null){_modal.gameObject.SetActive(false);Destroy(_modal.gameObject);}_modal=null;_content=null;_page="";Course.Paused=false;}
  private void Begin(string page,string title){UiFactory.HighContrast=P.HighContrast;Tap();if(_modal!=null){_modal.gameObject.SetActive(false);Destroy(_modal.gameObject);}_page=page;Course.Paused=true;
   _modal=UiFactory.Panel(_safe,"ModalBackdrop",page=="home"?Ivory:new Color(.035f,.09f,.12f,.24f),Vector2.zero,Vector2.one);
   float sw=_safe.rect.width,sh=_safe.rect.height,w=Mathf.Min(sw-24,sw>sh?820:460),h=Mathf.Min(sh-24,sw>sh?340:page=="checkpoint"?520:page=="banked"||page=="complete"||page=="tutorialComplete"?460:680),closeSize=UiMetrics.TargetSize(_safe,52),top=sw>sh?58:78;var card=UiFactory.Panel(_modal,"ModalCard",Ivory,Vector2.zero,Vector2.one);Place(card,(sw-w)/2,(sh-h)/2,w,h);
   var mark=UiFactory.Panel(card,"HeaderSignal",Blue,Vector2.zero,Vector2.one);Place(mark,16,16,3,28);
   var titleLabel=UiFactory.Label(card,"Title",title,25,Vector2.zero,Vector2.one,TextAnchor.MiddleLeft,Ink,FontStyle.Bold);Place((RectTransform)titleLabel.transform,30,10,w-46,34);
   var caption=UiFactory.Label(card,"Subtitle",page=="home"?T("30 ETAGEN · ","30 FLOORS · ")+P.Crystals+T(" MÜNZEN"," COINS"):page=="checkpoint"?T("KONTROLLPUNKT  /  SICHERN ODER BONUS","CHECKPOINT  /  BANK OR BONUS"):page=="banked"?T("RUNDE GESICHERT  /  NÄCHSTER AUFSTIEG","ROUND BANKED  /  NEXT CLIMB"):T("NEON SKYLINE  /  LIFT-LOBBY","NEON SKYLINE  /  LIFT LOBBY"),12,Vector2.zero,Vector2.one,TextAnchor.MiddleLeft,Ink);Place((RectTransform)caption.transform,30,42,w-46,18);caption.gameObject.SetActive(sw<=sh);
   var viewport=UiFactory.Panel(card,"Viewport",Color.clear,Vector2.zero,Vector2.one);viewport.GetComponent<Image>().raycastTarget=true;Place(viewport,16,top,w-32,h-top-closeSize-28);viewport.gameObject.AddComponent<RectMask2D>();
   var scroll=viewport.gameObject.AddComponent<ScrollRect>();scroll.horizontal=false;scroll.vertical=true;scroll.viewport=viewport;scroll.movementType=ScrollRect.MovementType.Clamped;
   var cg=new GameObject("Content",typeof(RectTransform),typeof(VerticalLayoutGroup),typeof(ContentSizeFitter));cg.transform.SetParent(viewport,false);_content=(RectTransform)cg.transform;_content.anchorMin=new Vector2(0,1);_content.anchorMax=Vector2.one;_content.pivot=new Vector2(.5f,1);_content.offsetMin=_content.offsetMax=Vector2.zero;
   var layout=cg.GetComponent<VerticalLayoutGroup>();layout.spacing=10;layout.childControlHeight=true;layout.childControlWidth=true;layout.childForceExpandHeight=false;layout.padding=new RectOffset(0,0,0,8);cg.GetComponent<ContentSizeFitter>().verticalFit=ContentSizeFitter.FitMode.PreferredSize;scroll.content=_content;
   var close=UiFactory.Button(card,"Close",T("ZURÜCK ZUM SPIEL","BACK TO GAME"),Blue,Color.white,Vector2.zero,Vector2.one,()=>{if(_page=="checkpoint")Course.Continue();else Close();});Place((RectTransform)close.transform,16,h-closeSize-14,w-32,closeSize);close.GetComponentInChildren<Text>().fontSize=18;
  }
  private void Row(string name,string label,Color color,Action action,bool enabled=true){var button=UiFactory.Button(_content,name,label,color==Gold?Gold:new Color(.07f,.12f,.17f),Color.white,Vector2.zero,Vector2.one,()=>{Tap();action?.Invoke();});button.gameObject.AddComponent<LayoutElement>().preferredHeight=UiMetrics.TargetSize(_safe,_safe.rect.width>_safe.rect.height?48:56);var labelText=button.GetComponentInChildren<Text>();labelText.fontSize=19;labelText.resizeTextMaxSize=19;labelText.alignment=TextAnchor.MiddleLeft;((RectTransform)labelText.transform).offsetMin=new Vector2(18,0);((RectTransform)labelText.transform).offsetMax=new Vector2(-14,0);var signal=UiFactory.Panel(button.transform,"Signal",color==Gold?Gold:Blue,Vector2.zero,Vector2.one);signal.GetComponent<Image>().raycastTarget=false;signal.anchorMin=new Vector2(0,.24f);signal.anchorMax=new Vector2(0,.76f);signal.offsetMin=new Vector2(0,0);signal.offsetMax=new Vector2(3,0);button.interactable=enabled;if(name=="RewardVideo")_watchButton=button;if(name=="RetryStore")_retryStoreButton=button;}
  private void Note(string label,int height=62){var t=UiFactory.Label(_content,"Description",label,19,Vector2.zero,Vector2.one,TextAnchor.MiddleCenter,Ink);t.gameObject.AddComponent<LayoutElement>().preferredHeight=height;}
  public void ShowHome(){if(Course.IsTransferring)return;if(Course.TutorialActive)Course.EndTutorial(false);if(_selectedRealm<0||_selectedRealm>P.UnlockedRealm)_selectedRealm=P.Realm;
   Begin("home","ONE MORE FLOOR");Canvas.ForceUpdateCanvases();var viewport=(RectTransform)_content.parent;viewport.GetComponent<ScrollRect>().vertical=false;_content.GetComponent<VerticalLayoutGroup>().enabled=false;_content.GetComponent<ContentSizeFitter>().enabled=false;_content.anchorMin=Vector2.zero;_content.anchorMax=Vector2.one;_content.offsetMin=_content.offsetMax=Vector2.zero;Canvas.ForceUpdateCanvases();
   float w=viewport.rect.width,h=viewport.rect.height,target=UiMetrics.TargetSize(_safe,52);bool wide=_safe.rect.width>_safe.rect.height;float dockH=target*2+8,heroH=wide?h:h-dockH-12,heroW=wide?w*.45f-8:w*.43f-4,chapterX=heroW+8,chapterW=w-chapterX;
   var hero=UiFactory.Panel(_content,"TowerPreview",new Color(.88f,.80f,.66f),Vector2.zero,Vector2.one);Place(hero,0,0,heroW,heroH);var art=LiftScenePreview.Create(hero,_selectedRealm);art.anchorMin=Vector2.zero;art.anchorMax=Vector2.one;art.offsetMin=art.offsetMax=Vector2.zero;
   string[] names={"Sunset","Neon","Skyline"};float chapterH=wide?Mathf.Max(target,h-dockH-12):(heroH-16)/3;
   for(int i=0;i<3;i++){int realm=i;bool unlocked=i<=P.UnlockedRealm;float cw=wide?(chapterW-12)/3:chapterW,cx=wide?chapterX+i*(cw+6):chapterX,cy=wide?0:i*(chapterH+8);var tab=UiFactory.Button(_content,"Realm"+i,"",Ink,Color.white,Vector2.zero,Vector2.one,()=>{_selectedRealm=realm;ShowHome();});Place((RectTransform)tab.transform,cx,cy,cw,chapterH);tab.interactable=unlocked;ChapterCityGraphic.Create(tab.transform,i);
    UiFactory.Label(tab.transform,"TowerLabel",names[i],wide?13:20,new Vector2(.03f,.47f),new Vector2(.39f,.90f),TextAnchor.MiddleCenter,Color.white,FontStyle.Bold);
    UiFactory.Label(tab.transform,"TowerIndex",unlocked?P.Stars[i]+" / 3 ★":"×",13,new Vector2(.03f,.16f),new Vector2(.39f,.47f),TextAnchor.MiddleCenter,Color.white,FontStyle.Bold);
    var edge=UiFactory.Panel(tab.transform,"Selected",i==_selectedRealm?Gold:Color.clear,new Vector2(.02f,0),new Vector2(.98f,.055f));edge.GetComponent<Image>().raycastTarget=false;
   }
   float dockX=wide?chapterX:0,dockY=wide?h-dockH:heroH+12,dockW=wide?chapterW:w;
   void Dock(int index,string name,string label,HudIcons.Kind icon,Action action){float cell=(dockW-16)/3;int col=index%3,row=index/3;var b=UiFactory.Button(_content,name,"",new Color(.91f,.84f,.71f),Ink,Vector2.zero,Vector2.one,()=>{Tap();action();});Place((RectTransform)b.transform,dockX+col*(cell+8),dockY+row*(target+8),cell,target);var iconPane=UiFactory.Panel(b.transform,"Icon",Color.clear,new Vector2(.04f,.26f),new Vector2(.26f,.74f));HudIcons.Add(iconPane,icon);foreach(var graphic in iconPane.GetComponentsInChildren<Graphic>()){graphic.raycastTarget=false;if(graphic is HudIcons)graphic.color=Ink;}UiFactory.Label(b.transform,"Name",label,13,new Vector2(.27f,.06f),new Vector2(.98f,.94f),TextAnchor.MiddleCenter,Ink,FontStyle.Bold);}
   Dock(0,"DailyChallenge",T("ROUTE","ROUTE"),HudIcons.Kind.Arrow,()=>{int seed=DateTime.UtcNow.DayOfYear%(P.UnlockedRealm+1);Course.StartRun(seed,true);Close();});Dock(1,"Style",T("STIL","STYLE"),HudIcons.Kind.Jump,ShowStyle);Dock(2,"Shop","SHOP",HudIcons.Kind.Crystal,ShowShop);Dock(3,"Daily",T("GESCHENK","GIFT"),HudIcons.Kind.Crystal,ShowDaily);Dock(4,"Achievements",T("ERFOLGE","AWARDS"),HudIcons.Kind.Arrow,ShowAchievements);Dock(5,"Settings",T("OPTIONEN","OPTIONS"),HudIcons.Kind.Menu,ShowSettings);
   var card=viewport.parent;var play=card.Find("Close").GetComponent<Button>();play.onClick.RemoveAllListeners();bool resume=!P.Completed&&!P.RunBanked&&_selectedRealm==P.Realm;play.GetComponentInChildren<Text>().text=resume?T("WEITER · ETAGE ","CONTINUE · FLOOR ")+(P.Step+1):T("AUFSTIEG STARTEN","START CLIMB");UiFactory.StyleButton(play,Gold);play.onClick.AddListener(()=>{if(!resume)Course.StartRun(_selectedRealm,false);Close();});var pr=(RectTransform)play.transform;float learnW=Mathf.Max(90,target);pr.anchoredPosition+=new Vector2(learnW+8,0);pr.sizeDelta-=new Vector2(learnW+8,0);
   var learn=UiFactory.Button(card,"Tutorial",T("LERNEN","LEARN"),Navy,Color.white,Vector2.zero,Vector2.one,StartTutorial);Place((RectTransform)learn.transform,16,((RectTransform)card).rect.height-target-14,learnW,target);learn.GetComponentInChildren<Text>().fontSize=16;
  }
  public void StartTutorial(){if(!Course.BeginTutorial())return;Close();Layout();UpdateCoach();UnityEngine.Camera.main?.GetComponent<CameraSystem.OrbitCamera>()?.FrameNow();}
  public void SkipTutorial(){if(Course.IsTransferring)return;Course.EndTutorial(false);ShowHome();UpdateCoach();}
  public void ShowTutorialComplete(){Begin("tutorialComplete",T("BEREIT FÜR DEN AUFSTIEG","READY TO CLIMB"));Note(T("Timing getroffen. Perfect gelandet. Münzen gesichert.\nDeine Übung ist abgeschlossen – wähle deinen Turm.","Timing learned. Perfect landed. Coins banked.\nPractice complete – choose your tower."),_safe.rect.width>_safe.rect.height?80:130);Row("TutorialPlay",T("ZUR LIFT-LOBBY","OPEN LIFT LOBBY"),Gold,ShowHome);UpdateCoach();}
  private void CreateCoach(){_coach=UiFactory.Panel(_safe,"TutorialCoach",new Color(.025f,.065f,.09f,.97f),Vector2.zero,Vector2.one);_coach.GetComponent<Image>().raycastTarget=false;_coachTitle=UiFactory.Label(_coach,"Lesson","",15,new Vector2(.04f,.57f),new Vector2(.76f,.96f),TextAnchor.MiddleLeft,Blue,FontStyle.Bold);_coachBody=UiFactory.Label(_coach,"Instruction","",14,new Vector2(.04f,.06f),new Vector2(.77f,.58f),TextAnchor.MiddleLeft,Color.white);var skip=UiFactory.Button(_coach,"SkipTutorial",T("ENDE","EXIT"),new Color(.06f,.12f,.16f),Color.white,Vector2.zero,Vector2.one,SkipTutorial);_coachSkip=skip;float target=UiMetrics.TargetSize(_safe,49);_coachSkipLabel=skip.GetComponentInChildren<Text>();_coachSkipLabel.fontSize=_coachSkipLabel.resizeTextMaxSize=13;Place((RectTransform)skip.transform,0,0,target,target);var r=(RectTransform)skip.transform;r.anchorMin=r.anchorMax=new Vector2(1,.5f);r.pivot=new Vector2(1,.5f);r.anchoredPosition=new Vector2(-6,0);_coach.gameObject.SetActive(false);}
  private void UpdateCoach(){if(_coach==null)return;_coach.gameObject.SetActive(Course.TutorialActive&&!ModalOpen);if(!Course.TutorialActive)return;var stage=Course.Tutorial.Stage;string title,body;switch(stage){case ElevatorTutorialStage.Timing:title=T("01 / TIMING","01 / TIMING");body=T("Warte auf die Bucht. Tippe bei LANDUNG MÖGLICH.","Wait for the bay. Tap during LANDING WINDOW.");break;case ElevatorTutorialStage.Perfect:title="02 / PERFECT";body=T("Triff die Mitte: Tippe im goldenen PERFECT-FENSTER.","Hit the centre: tap in the gold PERFECT WINDOW.");break;case ElevatorTutorialStage.Checkpoint:title=T("03 / KONTROLLPUNKT","03 / CHECKPOINT");body=T("Gut! Steige bis Etage 5 – dort kannst du Münzen sichern.","Nice! Reach the next checkpoint to bank your coins.");break;case ElevatorTutorialStage.Risk:title=T("04 / EINE ETAGE MEHR","04 / ONE MORE FLOOR");body=T("Bonus aktiv. Triff erneut – ein Fehlversuch verliert nur Runden-Coins.","Bonus active. Land again – a miss loses only round coins.");break;case ElevatorTutorialStage.Bank:title=T("05 / SICHER HEIM","05 / BANK IT");body=T("Weiter bis zum Kontrollpunkt. Sichere dann deine Münzen.","Climb to the next checkpoint. Then bank your coins.");break;default:title=T("03 / DEINE ENTSCHEIDUNG","03 / YOUR CHOICE");body=T("Sichern beendet die Runde. Weiter erhöht Risiko und Bonus.","Bank ends the round. Continue increases risk and bonus.");break;}_coachTitle.text=title;_coachBody.text=body;_coachSkipLabel.text=T("ENDE","EXIT");_coachSkip.interactable=!Course.IsTransferring;}
  public void ShowShop(){Begin("shop",T("DESIGN-SHOP","DESIGN SHOP"));Note(T("Sichere Münzen an Kontrollpunkten.\nFreigeschaltete Designs bleiben dauerhaft dein.","Bank coins at checkpoints.\nUnlocked designs remain yours."),76);StyleRows();CommerceRows();}
  public void ShowStyle(){Begin("style",T("DEIN LÄUFER","YOUR RUNNER"));StyleRows();}
  private void StyleRows(){string[] de={"Nachtläufer","Cyan-Puls","Sonnenkupfer","Auroraviolett","Goldener Pfad","Neonflügel","Nordlicht","Sternennacht"},en={"Night Runner","Cyan Pulse","Sun Copper","Aurora Violet","Golden Trail","Neon Wings","Northern Lights","Starry Night"};int[] prices={0,75,150,250};Color[] colors={new Color(.36f,.44f,.52f),Blue,new Color(1,.47f,.25f),new Color(.65f,.42f,1),Gold,new Color(.19f,.52f,1),new Color(.24f,.85f,.56f),new Color(.43f,.45f,.76f)};Canvas.ForceUpdateCanvases();float cellW=(_content.rect.width-10)/2,cellH=UiMetrics.TargetSize(_safe,94);var grid=new GameObject("DesignGrid",typeof(RectTransform),typeof(GridLayoutGroup),typeof(LayoutElement));grid.transform.SetParent(_content,false);var layout=grid.GetComponent<GridLayoutGroup>();layout.cellSize=new Vector2(cellW,cellH);layout.spacing=new Vector2(10,10);layout.constraint=GridLayoutGroup.Constraint.FixedColumnCount;layout.constraintCount=2;grid.GetComponent<LayoutElement>().preferredHeight=cellH*4+30;
   for(int i=0;i<8;i++){int style=i;var button=UiFactory.Button(grid.transform,"Style"+i,"",i==P.Style?new Color(.08f,.22f,.25f):new Color(.06f,.10f,.15f),Color.white,Vector2.zero,Vector2.one,()=>{Tap();if(Course.SelectStyle(style))Reopen();else Note(T("Nicht genug Münzen. Spiele die nächsten Etappen!","Not enough coins. Play the next steps!"));});button.interactable=P.Styles[i]||(i<4&&P.Crystals>=prices[i]);var swatch=UiFactory.Panel(button.transform,"DesignSwatch",colors[i],new Vector2(.08f,.64f),new Vector2(.24f,.85f));swatch.GetComponent<Image>().raycastTarget=false;UiFactory.Label(button.transform,"DesignName",T(de[i],en[i]),16,new Vector2(.08f,.32f),new Vector2(.94f,.64f),TextAnchor.MiddleLeft,Color.white,FontStyle.Bold);UiFactory.Label(button.transform,"DesignStatus",P.Style==i?T("AKTIV","ACTIVE"):P.Styles[i]?T("AUSWÄHLEN","SELECT"):i>=4?T("EXTRA-DESIGN","EXTRA DESIGN"):prices[i]+T(" MÜNZEN"," COINS"),12,new Vector2(.08f,.08f),new Vector2(.94f,.34f),TextAnchor.MiddleLeft,i==P.Style?Blue:Muted);}
  }
  public void AttachCommerce(){Course.Store.Changed+=CommerceChanged;Course.Videos.Changed+=CommerceChanged;}
  private void CommerceChanged(){Refresh();if(ShopOpen)ShowShop();}
  private void CommerceRows(){var store=Course.Store;var videos=Course.Videos;if(store==null||videos==null)return;
   Note(T("EXTRA-DESIGNS · FREIWILLIG","EXTRA DESIGNS · OPTIONAL"),52);
   void Product(string id,string title,string description){Note(description,76);var price=store.Price(id);Row(id,title+" · "+(store.Owned(id)?T("GEKAUFT","OWNED"):string.IsNullOrWhiteSpace(price)?T("NICHT VERFÜGBAR","UNAVAILABLE"):price),Purple,()=>store.Buy(id),store.CanBuy(id));}
   Product(Kamilunavo.OneMoreFloor.Monetization.CommerceRules.Starter,T("STARTERPAKET","STARTER PACK"),T("Goldener Pfad als dauerhaftes Design und einmalig 500 Münzen.","Golden Trail permanent design and 500 coins once."));
   Product(Kamilunavo.OneMoreFloor.Monetization.CommerceRules.Collection,T("NEONKOLLEKTION","NEON COLLECTION"),T("Drei dauerhafte Designs: Neonflügel, Nordlicht und Sternennacht.","Three permanent designs: Neon Wings, Northern Lights and Starry Night."));
   Note(store.Status,72);if(!store.Ready)Row("RetryStore",T("STORE ERNEUT VERBINDEN","RECONNECT STORE"),Blue,store.RetryConnection,store.CanRetry);Row("Restore",T("KÄUFE WIEDERHERSTELLEN","RESTORE PURCHASES"),Navy,store.Restore,store.Ready&&!store.Busy);
   Note(videos.Status,76);int remaining=Kamilunavo.OneMoreFloor.Monetization.RewardRules.Remaining(P,DateTime.UtcNow);Row("RewardVideo",T("FREIWILLIGES VIDEO · +50 MÜNZEN","OPTIONAL VIDEO · +50 COINS")+" · "+remaining+"/5",Blue,videos.Watch,videos.CanWatch);
   Row("PrepareVideo",T("VIDEO VORBEREITEN","PREPARE VIDEO"),Navy,videos.Prepare,!videos.IsPresenting);if(videos.PrivacyRequired)Row("PrivacyOptions",T("DATENSCHUTZEINSTELLUNGEN","PRIVACY OPTIONS"),Navy,videos.ShowPrivacy,!videos.IsPresenting);
   if(Kamilunavo.OneMoreFloor.Monetization.MonetizationConfig.Load().InternalTestAds)Note(T("Interner Test: Videos verwenden Testanzeigen.","Internal test: videos use test ads."),62);
  }
  public void ShowDaily(){Begin("daily",T("TAGESGESCHENK","DAILY GIFT"));bool ready=string.CompareOrdinal(FloorRules.Day(DateTime.UtcNow),P.DailyDay)>0;Note(T("Einmal je UTC-Tag. Deine Serie erhöht die Belohnung bis auf 160 Münzen.","Once each UTC day. Your streak increases the reward up to 160 coins."),100);Note(T("Serie: ","Streak: ")+P.DailyStreak+" / 7");Row("ClaimDaily",ready?T("GESCHENK ABHOLEN","CLAIM GIFT"):T("HEUTE BEREITS ABGEHOLT","ALREADY CLAIMED TODAY"),new Color(1,.4f,.06f),()=>{Course.ClaimDaily();ShowDaily();},ready);}
  public void ShowSettings(){Begin("settings",T("EINSTELLUNGEN","SETTINGS"));void Toggle(Action act){act();FloorSave.Save(P);Refresh();ShowSettings();}
   Row("TutorialReplay",T("TUTORIAL ERNEUT SPIELEN","REPLAY TUTORIAL"),Blue,StartTutorial);Row("Language",T("SPRACHE: DEUTSCH","LANGUAGE: ENGLISH"),Blue,()=>Toggle(()=>P.Language=P.Language=="de"?"en":"de"));
   Row("Sound",T("TON: ","SOUND: ")+On(P.Sound),Navy,()=>Toggle(()=>P.Sound=!P.Sound));Row("Haptics",T("HAPTIK: ","HAPTICS: ")+On(P.Haptics),Navy,()=>Toggle(()=>P.Haptics=!P.Haptics));Row("Motion",T("WENIGER BEWEGUNG: ","REDUCED MOTION: ")+On(P.ReducedMotion),Navy,()=>Toggle(()=>P.ReducedMotion=!P.ReducedMotion));Row("Contrast",T("HOHER KONTRAST: ","HIGH CONTRAST: ")+On(P.HighContrast),Navy,()=>Toggle(()=>P.HighContrast=!P.HighContrast));}
  private string On(bool b)=>b?T("AN","ON"):T("AUS","OFF");
  public void ShowAchievements(){Begin("achievements",T("ERFOLGE","ACHIEVEMENTS"));Note(T("Dein Fortschritt wird auf diesem Gerät gespeichert.","Your progress is saved on this device."));Note(T("Beste Etage: ","Best floor: ")+(P.BestFloor+1)+" / 30 · "+T("Punkte: ","Score: ")+P.BestScore.ToString("N0"));string Mark(bool done)=>done?T("GESCHAFFT · ","DONE · "):T("ZIEL · ","GOAL · ");Note(Mark(P.Stars[0]>0)+T("Erster Turm","First tower"));Note(Mark(P.Stars[0]>0&&P.Stars[1]>0&&P.Stars[2]>0)+T("Alle drei Türme","All three towers"));Note(Mark(P.BestPerfects==29)+T("29 perfekte Landungen in einer Route","29 perfect landings in one route"));Note(Mark(P.BestDailyStreak==7)+T("Sieben Tage in Folge","Seven days in a row"));}
  public void ShowCompletion(){Begin("complete",T("TURM GESCHAFFT!","TOWER CLEARED!"));int stars=P.Falls>0?1:P.Elapsed<=240?3:2;Note(stars+" / 3 "+T("Sterne","stars")+"\n"+P.Perfects+" "+T("perfekte Landungen","perfect landings")+" · "+P.Falls+" "+T("Stürze","falls"),_safe.rect.width>_safe.rect.height?52:90);if(!P.Challenge&&P.Realm<2)Row("NextRealm",T("NÄCHSTER TURM","NEXT TOWER"),Blue,()=>{Course.StartRun(P.Realm+1,false);Close();});Row("Replay",T("NOCH EINMAL","PLAY AGAIN"),Purple,()=>{Course.StartRun(P.Realm,P.Challenge);Close();});Row("Home",T("ALLE TÜRME","ALL TOWERS"),Navy,ShowHome);}
  private void RoundSummary(string name,string value,string detail,Color accent){var panel=UiFactory.Panel(_content,name,new Color(.91f,.84f,.71f),Vector2.zero,Vector2.one);panel.gameObject.AddComponent<LayoutElement>().preferredHeight=UiMetrics.TargetSize(_safe,_safe.rect.width>_safe.rect.height?52:90);UiFactory.Label(panel,"Amount",value,27,new Vector2(.05f,.36f),new Vector2(.94f,.96f),TextAnchor.MiddleLeft,Ink,FontStyle.Bold);UiFactory.Label(panel,"Detail",detail,14,new Vector2(.05f,.08f),new Vector2(.94f,.40f),TextAnchor.MiddleLeft,Ink);}
  public void ShowCheckpoint(){if(Course.TutorialActive)Course.Tutorial.AtCheckpoint();Begin("checkpoint",T("SICHERN ODER WEITER?","BANK OR KEEP CLIMBING?"));bool canBank=!Course.TutorialActive||Course.Tutorial.Stage==ElevatorTutorialStage.Choice||Course.Tutorial.Stage==ElevatorTutorialStage.Bank;bool wide=_safe.rect.width>_safe.rect.height;float target=UiMetrics.TargetSize(_safe,52),sw=_safe.rect.width,sh=_safe.rect.height;var card=(RectTransform)_modal.Find("ModalCard");float w=card.rect.width,h=Mathf.Min(sh-24,wide?target+166:target*2+210);Place(card,(sw-w)/2,sh-h-12,w,h);card.Find("Subtitle").gameObject.SetActive(false);card.Find("HeaderSignal").gameObject.SetActive(false);var title=(RectTransform)card.Find("Title");Place(title,16,6,w-32,38);title.GetComponent<Text>().fontSize=22;
   var viewport=(RectTransform)_content.parent;Place(viewport,16,46,w-32,h-46-(wide?target+26:target*2+34));viewport.GetComponent<ScrollRect>().vertical=false;
   var risk=UiFactory.Panel(_content,"RiskSummary",Color.clear,Vector2.zero,Vector2.one);risk.gameObject.AddComponent<LayoutElement>().preferredHeight=26;UiFactory.Label(risk,"RiskAmount",P.PendingCoins+T(" MÜNZEN IM RISIKO"," COINS AT RISK")+(Course.TutorialActive?T(" · ÜBUNG"," · PRACTICE"):""),18,Vector2.zero,Vector2.one,TextAnchor.MiddleCenter,Ink,FontStyle.Bold);
   var compare=UiFactory.Panel(_content,"FloorComparison",new Color(.92f,.85f,.72f),Vector2.zero,Vector2.one);compare.gameObject.AddComponent<LayoutElement>().preferredHeight=wide?50:68;
   for(int i=0;i<2;i++){var thumb=UiFactory.Panel(compare,i==0?"CurrentFloor":"NextFloor",Ink,new Vector2(i==0?.01f:.54f,.04f),new Vector2(i==0?.46f:.99f,.96f));ChapterCityGraphic.Create(thumb,P.Realm);UiFactory.Label(thumb,"FloorLabel",(i==0?T("ETAGE\n","FLOOR\n"):T("WEITER\n","NEXT\n"))+(P.Step+1+i),14,new Vector2(.02f,.05f),new Vector2(.38f,.95f),TextAnchor.MiddleCenter,Color.white,FontStyle.Bold);}
   UiFactory.Label(compare,"DecisionArrow","›",32,new Vector2(.46f,0),new Vector2(.54f,1),TextAnchor.MiddleCenter,Ink,FontStyle.Bold);
   var bank=card.Find("Close").GetComponent<Button>();bank.name="Bank";bank.onClick.RemoveAllListeners();bank.onClick.AddListener(Course.BankRun);bank.interactable=canBank;UiFactory.StyleButton(bank,Gold);bank.GetComponentInChildren<Text>().text=canBank?T("MÜNZEN SICHERN · ","BANK COINS · ")+P.PendingCoins:T("ERST PERFECT LANDEN","LAND A PERFECT FIRST");
   var more=UiFactory.Button(card,"Continue",T("EINE ETAGE MEHR · ×","ONE MORE FLOOR · ×")+(1+Mathf.Min(5,(P.Step+1)/5)),Navy,Color.white,Vector2.zero,Vector2.one,Course.Continue);more.GetComponentInChildren<Text>().fontSize=18;
   if(wide){float cell=(w-40)/2;Place((RectTransform)bank.transform,16,h-target-14,cell,target);Place((RectTransform)more.transform,24+cell,h-target-14,cell,target);}else{Place((RectTransform)bank.transform,16,h-target*2-22,w-32,target);Place((RectTransform)more.transform,16,h-target-14,w-32,target);}
  }
  public void ShowBanked(){Begin("banked",T("MÜNZEN GESICHERT!","COINS BANKED!"));RoundSummary("BankedSummary",P.Crystals+T(" MÜNZEN"," COINS"),T("DEIN GUTHABEN · DAUERHAFT GESICHERT","YOUR WALLET · SAFELY BANKED"),Gold);if(_safe.rect.width<=_safe.rect.height)Note(T("Dein nächster Aufstieg wartet.","Your next climb is waiting."),52);Row("Replay",T("NOCH EINE RUNDE","ONE MORE ROUND"),Gold,()=>{Course.StartRun(P.Realm,P.Challenge);Close();});Row("Home",T("TÜRME & DESIGNS","TOWERS & DESIGNS"),Blue,ShowHome);}
  private void Reopen(){switch(_page){case "tutorialComplete":ShowTutorialComplete();break;case "banked":ShowBanked();break;case "checkpoint":ShowCheckpoint();break;case "settings":ShowSettings();break;case "daily":ShowDaily();break;case "style":ShowStyle();break;case "shop":ShowShop();break;case "complete":ShowCompletion();break;case "achievements":ShowAchievements();break;default:ShowHome();break;}}
 }
}
