#if UNITY_EDITOR
using System;
using System.Reflection;
using UnityEngine;
using UnityEngine.UI;
using Kamilunavo.OneMoreFloor.Core;
using Kamilunavo.OneMoreFloor.Gameplay;
using Kamilunavo.OneMoreFloor.UI;
public static class FloorMenuValidation
{
 static int checks;
 static void Check(bool valid,string name){checks++;if(!valid)throw new Exception("LIFT_MENU: "+name);}
 public static void Validate(){checks=0;ValidateGraphicFactories();ValidateButtonContrast();ValidateDeckPresentation();var legacy=FloorSave.Parse("{\"Schema\":1,\"Crystals\":428,\"Step\":7,\"Checkpoint\":4}");Check(!legacy.TutorialCompleted&&legacy.Crystals==428&&legacy.Step==7,"missing tutorial field retains old profile");legacy.TutorialCompleted=true;var copy=FloorSave.Parse(JsonUtility.ToJson(legacy));Check(copy.TutorialCompleted&&copy.Crystals==428&&copy.Step==7,"tutorial completion round trips without progress migration");
  var lesson=new ElevatorTutorial();lesson.Landing(false,1);lesson.AtCheckpoint();Check(lesson.Stage==ElevatorTutorialStage.Perfect,"checkpoint cannot replace actual perfect");lesson.Landing(true,2);lesson.AtCheckpoint();lesson.Risk();lesson.Landing(true,5);lesson.AtCheckpoint();lesson.Banked();Check(lesson.Complete,"actual risk landing then banking completes");
  foreach(var size in new[]{new Vector2(375,627),new Vector2(393,759),new Vector2(430,839),new Vector2(734,343),new Vector2(809,372),new Vector2(280,580)})foreach(var lang in new[]{"de","en"})LayoutFixture(size,lang);Debug.Log("LIFT_MENU_EDITOR_PASS checks="+checks);
 }
 static void ValidateDeckPresentation(){var root=new GameObject("DeckPresentationProbe");try{Kamilunavo.OneMoreFloor.Visuals.PlatformArt.Build(root.transform,4,0);Check(root.GetComponentsInChildren<Collider>().Length==1,"industrial decoration adds no gameplay collision");Check(root.transform.Find("ServiceInlay")!=null&&root.transform.Find("CarriageRoller")!=null&&root.transform.Find("LiftControlDisplay")!=null,"authored vent/carriage/control kit exists");var collision=root.GetComponentInChildren<BoxCollider>();Check(collision.size==new Vector3(4.6f,.70f,3.6f)&&collision.center==new Vector3(0,.25f,0),"landing surface dimensions remain authoritative");}finally{UnityEngine.Object.DestroyImmediate(root);}}
 static void ValidateButtonContrast(){var canvas=UiFactory.Canvas();try{foreach(var background in new[]{new Color(.07f,.12f,.17f),new Color(.06f,.63f,.76f),new Color(1,.73f,.12f),new Color(1,.4f,.06f)}){var button=UiFactory.Button(canvas.transform,"ContrastProbe","READABLE",background,Color.white,Vector2.zero,Vector2.one,null);CheckButtonContrast(button,"factory");UnityEngine.Object.DestroyImmediate(button.gameObject);}}finally{UnityEngine.Object.DestroyImmediate(canvas.gameObject);}}
 static float Contrast(Color a,Color b){float Linear(float c)=>c<=.04045f?c/12.92f:Mathf.Pow((c+.055f)/1.055f,2.4f);float L(Color c)=>.2126f*Linear(c.r)+.7152f*Linear(c.g)+.0722f*Linear(c.b);return (Mathf.Max(L(a),L(b))+.05f)/(Mathf.Min(L(a),L(b))+.05f);}
 static void CheckButtonContrast(Button button,string pose){var image=button.GetComponent<Image>();foreach(var state in new[]{button.colors.normalColor,button.colors.highlightedColor,button.colors.pressedColor,button.colors.selectedColor,button.colors.disabledColor}){Color surface=image.color*state*button.colors.colorMultiplier;surface.a=1;foreach(var text in button.GetComponentsInChildren<Text>())if(!string.IsNullOrWhiteSpace(text.text))Check(Contrast(surface,text.color)>=4.5f,pose+" all button states readable "+button.name+"/"+text.name);}}
 static void ValidateGraphicFactories(){var canvas=UiFactory.Canvas();try{var pane=UiFactory.Panel(canvas.transform,"ClippedGraphicProbe",Color.white,Vector2.zero,Vector2.one);pane.gameObject.AddComponent<RectMask2D>();UiFactory.Label(pane,"Label","Graphic probe",16,Vector2.zero,Vector2.one,TextAnchor.MiddleCenter,Color.white);HudIcons.Add(pane,HudIcons.Kind.Menu);LiftTowerGraphic.Create(pane,0);ScenicCityGraphic.Create(pane,0);Kamilunavo.OneMoreFloor.Input.VirtualJoystick.Create(pane,Vector2.zero,Vector2.one);Kamilunavo.OneMoreFloor.Input.PressButton.Create(pane,"Circle",Vector2.zero,Vector2.one);Kamilunavo.OneMoreFloor.Input.PressButton.Create(pane,"Wide",Vector2.zero,Vector2.one,true);foreach(var graphic in canvas.GetComponentsInChildren<Graphic>())Check(graphic.GetComponent<CanvasRenderer>()!=null,"graphic factory owns CanvasRenderer "+graphic.name);Canvas.ForceUpdateCanvases();}finally{UnityEngine.Object.DestroyImmediate(canvas.gameObject);}}
 static void LayoutFixture(Vector2 size,string language){var root=new GameObject("LiftMenuProbe");Canvas canvas=null;try{var course=root.AddComponent<FloorCourse>();var p=new FloorProfile{Language=language,UnlockedRealm=2,TimingVersion=1,Crystals=428};typeof(FloorCourse).GetField("<Profile>k__BackingField",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(course,p);course.Player=new GameObject("Player").transform;course.Player.SetParent(root.transform);var hud=root.AddComponent<FloorHud>();hud.Initialize(course);var safe=(RectTransform)typeof(FloorHud).GetField("_safe",BindingFlags.Instance|BindingFlags.NonPublic).GetValue(hud);canvas=safe.GetComponentInParent<Canvas>();canvas.GetComponent<CanvasScaler>().enabled=false;canvas.scaleFactor=3;UiMetrics.QaPointScale=3;safe.GetComponent<SafeAreaFitter>().enabled=false;safe.anchorMin=safe.anchorMax=new Vector2(.5f,.5f);safe.sizeDelta=size;typeof(FloorHud).GetMethod("Layout",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(hud,null);var modalField=typeof(FloorHud).GetField("_modal",BindingFlags.Instance|BindingFlags.NonPublic);UnityEngine.Object.DestroyImmediate(((RectTransform)modalField.GetValue(hud)).gameObject);modalField.SetValue(hud,null);hud.ShowHome();Canvas.ForceUpdateCanvases();
   var card=(RectTransform)safe.Find("ModalBackdrop/ModalCard");var viewport=(RectTransform)card.Find("Viewport");Check(!viewport.GetComponent<ScrollRect>().vertical,size+" home uses fixed hierarchy");var content=viewport.Find("Content");Check(content.Find("TowerPreview/LiftElevation")!=null,size+" authored lift preview exists");Check(content.Find("TowerPreview/ScenicCity")!=null,size+" scenic tower image exists");
   Rect usable=UiMetrics.ScreenRect(safe),body=UiMetrics.ScreenRect(viewport);var buttons=card.GetComponentsInChildren<Button>();foreach(var b in buttons){CheckButtonContrast(b,size+" "+language+" home");Rect r=UiMetrics.ScreenRect((RectTransform)b.transform);Check(r.width/3>=47.999f&&r.height/3>=47.999f,size+" "+language+" >=48 points "+b.name);Check(Inside(usable,r),size+" safe bounds "+b.name);if(b.transform.IsChildOf(content))Check(Inside(body,r),size+" visible without scrolling "+b.name);}
   for(int a=0;a<buttons.Length;a++)for(int b=a+1;b<buttons.Length;b++)Check(!UiMetrics.ScreenRect((RectTransform)buttons[a].transform).Overlaps(UiMetrics.ScreenRect((RectTransform)buttons[b].transform)),size+" controls never overlap "+buttons[a].name+"/"+buttons[b].name);
   Check(Inside(body,UiMetrics.ScreenRect((RectTransform)content.Find("TowerPreview"))),size+" hero inside viewport");
   UnityEngine.Object.DestroyImmediate(card.parent.gameObject);p.Step=p.Checkpoint=4;p.PendingCoins=12;p.CheckpointDecisionPending=true;hud.ShowCheckpoint();Canvas.ForceUpdateCanvases();CheckPage("checkpoint");Check(safe.Find("ModalBackdrop/ModalCard/Viewport/Content/RiskSummary")!=null,"risk summary presents amount and checkpoint");UnityEngine.Object.DestroyImmediate(safe.Find("ModalBackdrop").gameObject);p.CheckpointDecisionPending=false;p.RunBanked=true;hud.ShowBanked();Canvas.ForceUpdateCanvases();CheckPage("banked");Check(safe.Find("ModalBackdrop/ModalCard/Viewport/Content/BankedSummary")!=null,"result summary presents banked wallet");UnityEngine.Object.DestroyImmediate(safe.Find("ModalBackdrop").gameObject);hud.ShowSettings();Canvas.ForceUpdateCanvases();CheckPage("settings");UnityEngine.Object.DestroyImmediate(safe.Find("ModalBackdrop").gameObject);hud.ShowCompletion();Canvas.ForceUpdateCanvases();CheckPage("complete");
   void CheckPage(string page){var current=(RectTransform)safe.Find("ModalBackdrop/ModalCard");foreach(var button in current.GetComponentsInChildren<Button>()){CheckButtonContrast(button,size+" "+language+" "+page);Rect r=UiMetrics.ScreenRect((RectTransform)button.transform);Check(r.width/3>=47.999f&&r.height/3>=47.999f,size+" "+page+" >=48 points "+button.name);if(page=="checkpoint"||page=="banked")Check(Inside(UiMetrics.ScreenRect(current.Find("Viewport") as RectTransform),r)||!button.transform.IsChildOf(current.Find("Viewport")),size+" "+page+" decision remains in card");}}
  }finally{UiMetrics.QaPointScale=null;if(canvas!=null)UnityEngine.Object.DestroyImmediate(canvas.gameObject);UnityEngine.Object.DestroyImmediate(root);}}
 static bool Inside(Rect outer,Rect inner)=>inner.xMin>=outer.xMin-.5f&&inner.yMin>=outer.yMin-.5f&&inner.xMax<=outer.xMax+.5f&&inner.yMax<=outer.yMax+.5f;
}
#endif
