--!strict

return table.freeze({
	table.freeze({ Name = "FloorAction", Kind = "Event" }),
	table.freeze({ Name = "FloorState", Kind = "Event" }),
	table.freeze({ Name = "CosmeticAction", Kind = "Event" }),
	table.freeze({ Name = "CosmeticState", Kind = "Event" }),
	table.freeze({ Name = "CosmeticQuery", Kind = "Function" }),
	table.freeze({ Name = "MonetizationAction", Kind = "Event" }),
	table.freeze({ Name = "MonetizationState", Kind = "Event" }),
	table.freeze({ Name = "MonetizationQuery", Kind = "Function" }),
})
